image: openjdk:13-jdk-alpine3.10

stages:
  - build
  - test
  - coverage
  - codecov

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle

build:
  stage: build
  script:
    - ./gradlew classes testClasses -Dorg.gradle.internal.repository.max.tentavies=10 -Dorg.gradle.internal.repository.initial.backoff=500
  artifacts:
    paths:
      - build/

lint:
  stage: test
  script:
    - ./gradlew ktlintCheck

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/

coverage:
  stage: coverage
  script:
    - ./gradlew jacocoTestReport
  dependencies:
    - test
  artifacts:
    paths:
      - build/

codecov:
  image: bash:5.0.17
  stage: codecov
  before_script:
    - apk update && apk add curl
  script:
    - bash <(curl -s https://codecov.io/bash) -Z -t $CODECOV_TOKEN
  dependencies:
    - coverage
