image: openjdk:13-jdk-alpine3.10

stages:
  - test
  - coverage
  - codecov

lint:
  stage: test
  script:
    - ./gradlew ktlintCheck

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/

coverage:
  stage: coverage
  script:
    - ./gradlew jacocoTestReport
  dependencies:
    - test
  artifacts:
    paths:
      - build/

codecov:
  image: bash:5.0.17
  stage: codecov
  before_script:
    - apk update && apk add curl
  script:
    - bash <(curl -s https://codecov.io/bash) -Z
  dependencies:
    - coverage
