image: openjdk:13-jdk-alpine3.10

stages:
  - build
  - test

lint:
  stage: build
  script:
    - ./gradlew ktlintCheck

coverage:
  stage: test
  script:
    - ./gradlew jacocoTestReport

codecov:
  image: bash:5.0.17
  stage: test
  script:
    - bash <(curl -s https://codecov.io/bash)
